backend:
  name: github
  branch: master
  repo: csellis/blog

media_folder: static/img
public_folder: /img

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Team Member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }